### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#117]
https://oslc.github.io/foobar/

Right now it is using an old theme, please replace it with something in the style of the OSLC theme.

**Comment by LeoTrujillo** [comment]
yes, sure. Working on it

**Comment by brianking** [comment]
Might want to check other error code pages as well.

**Comment by LeoTrujillo** [comment]
@brianking I made the 404 template and added styles, in localhost this is not working because we need to configure the server, according of Hugo documentation if the page is in github pages is not necessary configure anything, automatically the template renders when the url or the page doesn't exist.

https://gohugo.io/templates/404/

here is the documentation, I don't know what happen but now github is not render the template maybe we can wait a little time

**Comment by brianking** [comment]
Issues seem to be fixed, looks good to me now. Closing.
