### ISSUE TITLE
Search not working on live site

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#126]
Neither the Resources nor News search are working on oslc.github.io. They work on on localhost.

Without know too much how it works, one theory I have is that the paths assigned in the json files are not resolving in a live environment.

**Comment by jailandrade** [comment]
I'll work in this first thing monday morning

**Comment by jailandrade** [comment]
The paths asigned for the files are `Site.BaseUrl/resources/resources.json` and `Site.BaseUrl/news/news.json`. I can access to [https://oslc.github.io/news/news.json](https://oslc.github.io/news/news.json) but not to [https://oslc.github.io/resources/resources.json](https://oslc.github.io/resources/resources.json), therefore I think the problem is related to #127. With the changes from the weekend we need to run `node search` and `node resources` to generate both files. I think is the fix for this bug.

**Comment by jailandrade** [comment]
This inside the `static-src` folder

**Comment by brianking** [comment]
@jailandrade Did you run the conversions again yet? This is still not working for me.

**Comment by jailandrade** [comment]
Ok, I found what was the problem, I sent a change, can you deploy again to test?

**Comment by brianking** [comment]
Yes, working now. Is it automated for new content?

**Comment by jailandrade** [comment]
still not, about this, which will be the server to launch in production? Digital Ocean or Github Pages?

**Comment by brianking** [comment]
Digital Ocean

**Comment by jailandrade** [comment]
I will prepare a script to launch the task with every deployment, to generate the content automaticalley, but this task its also related to #133 so when I finish that task I'll integrate the script.

**Comment by brianking** [comment]
@jailandrade What's the status of this one. It is working for me on the live site now both on Resources and News. What about the script to generate the json?

**Comment by jailandrade** [comment]
I have to modify the script to include tags, author and date attributes.

**Comment by jailandrade** [comment]
I'll close this to continue working on #133

**Comment by brianking** [comment]
Agreed, closing.
