### ISSUE TITLE
Tweaks and Fixes to Resources Filtering

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#127]
As search and filtering work independently:

- [x] Filtering is broken, needs to be fixed
- [x] Move Search button over beside the search box
- [x] Remove duplicate 'Video' entry in the dropdown
- [x] Remove 'Podcast' entry for now as we will not launch with any of these. I will also remove the sample podcast resources we have.

**Comment by brianking** [comment]
@jailandrade can you please fix the two outstanding tasks in this issue.

**Comment by jailandrade** [comment]
Filtering is not broken, it was an error with the process to generate the files. I created `content-src/search.js` and `content-src/resources.js`, so we need to run each file with node.

Also, note that the search works with the `uri`(this is the name of the file), `title`, `content` and `tag`, and the filtering here works differently from the news page, here it doesn't open a new page. 

If we have a `uri` with the name of a category/tag the `uri` will appear in the search. I think the best approach it's to name the file anything rather than the category, a good idea would be to name the file with the title of the post, eg: `this-is-the-title.md`

**Comment by brianking** [comment]
TODO:

* Only filter by category, not by text
* Further testing and fixes as necessary

**Comment by brianking** [comment]
TODO: Make sure filtering only loads items from that category, and not items that contain that text.

This is what happens, for example, when you select 'Tool'. Also an article and tutorial appear, and they should not.

![firefox_screenshot_2017-09-15t13-11-12 216z](https://user-images.githubusercontent.com/114116/30483735-39608ae4-9a28-11e7-930e-9dfaf906eb9c.png)

**Comment by jailandrade** [comment]
I'll update this script to work differently

**Comment by jailandrade** [comment]
I have to increase the number of items in the pagination to solve this.

**Comment by jailandrade** [comment]
I think this task it's done, @brianking can you confirm?

**Comment by brianking** [comment]
So I think there are still 2 fixes needed here:

1. Add an 'All' option to the dropdown, that when selected basically clears the filter.

2. Bug: Select an option - filtering works. Reload the page. The item remains selected in the dropdown, but all resources show. When the page reloads, we should either respect what is in the dropdown, or reset the dropdown and show all.

**Comment by brianking** [comment]
@jailandrade any update on the issue 2 above about filtering on page reloading? Did you say it is only a problem in Firefox? Is there a potential fix?

**Comment by jailandrade** [comment]
I can set up the default value to all, it works in Firefox

**Comment by jailandrade** [comment]
I already did https://github.com/OSLC/oslc-site-hugo/commit/feddf944867bf1237bb3962c7899d323e603c3de

**Comment by brianking** [comment]
Works for me too now in Firefox. Closing!
