### ISSUE TITLE
Updated Homepage Content

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#158]
Update the homepage with content from this document. It should replace everything there already, except the news section which should stay.

https://docs.google.com/presentation/d/1vDfrR4e5tstnYvmcV13_PGs__VQKHyz9UtFSzBbJaA0/edit?usp=sharing

**Comment by brianking** [comment]
I've checked in first pass at this. Some notes:

* All content is not in yet, I got as far as Slide 6
* I just used styles that were in existing partials on the stage. We might want to consider renaming the classes or creating new ones ... as needed
* Image and text are not centering up correctly in all sections, e.g. 'The OSLC Core Specification' section
* Most, if not all, images will have to be re-done. We can open a new issue for that.
* I made sure all sections have different background colours, but the flow might not be the best one.

**Comment by gabrielfdac** [comment]
1 - Glad to see that the existing styles were somewhat easy to reuse.
2 - The images are centering correctly, I checked the source code and did some tests. In you example I believe it is a visual illusion caused by the non-symmetric image in that section.
3 - For the images that have to be done, please do make a new issue from them.
4 - We can discuss more about the flow if necessary. Overall looks ok to me. Maybe after improving the images we'd have a better feel for it.

**Comment by brianking** [comment]
2. I did some more work Friday to center the images. I had to tinker a little with CSS. See the second commit linked just above your comment.
3. Will do
4. I also made changes there, just going between white and the shaded backgrounds. I removed the dark blue background that was there previously for resoures.

**Comment by gabrielfdac** [comment]
2 and 4. I guess I came late to the party. Either way we can readjust as we go.

**Comment by brianking** [comment]
Separate issues opened for what is remaining, so closing this.
