### ISSUE TITLE
New Namespaces / Vocabularies Page

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#16]
Old page: http://open-services.net/ns/ redirects to http://open-services.net/wiki/core/Vocabulary-index/. This is the root page for accessing the vocabularies. That URL should be redirected to the page described by the following notes.

(Content to follow)

Questions:
        ✓        Do we need to support automatic conversion of text/turtle to RDF/XML and/or JSON-LD? Or can we simply provide the Turtle and users can translate it themselves with readily available converters as needed? Naming guidance indicates Turtle is preferred, and doesn’t say anything else is required. However, the old table only provided RDF/XML. Only Turtle will be accessed.
        ✓        Move OSLC Core URI Naming Guidance to the Core TC Wiki. It is possible to access the OSLC Core TC Wiki without logging in.

**Comment by brianking** [comment]
@jamsden I don't think the content actually did come across as intended in the email I received. I don't see a table for example.

Do you have a screenshot of the proposed design?

**Comment by jamsden** [comment]
There is not table in the document I emailed - that from Apple Notes which doesn't yet support tables (oddly). There is no sreenshot on the layout - I focused on the content design, not the visual design.

**Comment by brianking** [comment]
Hacking on this here:
https://docs.google.com/document/d/1DRFoH-HOU6pfMIakgrU_kAs5KDBHBhKM7b1xQjCIGRk/edit?usp=sharing

Have sent message to @jamsden seeking clarification on some things.

**Comment by brianking** [comment]
@jamsden In relation to the new content you sent me via email, I have some questions.

1. You have a ‘Contents’ section that seems to be blank. Are the sections below supposed to be sub-sections of that, or can I remove it?

2. The Namespaces table
Apart from Core 3.0, are there any that are different from the table in the [current page](http://open-services.net/wiki/core/Vocabulary-index/)?
Can you clarify exactly what else should be different in the new table vs the current?

3. The 'Specifications, Vocabularies and Constraints’ section
Will there be links for all these properties for all vocabularies?
Where can I find these, is there a listing for all of them somewhere?

4. Change Management
Where can I find these files for each vocabulary?
Can you give an example of how this section might look like?

**Comment by brianking** [comment]
@jamsden 

The skeleton file for you to fill out is now checked in at:
https://github.com/OSLC/oslc-site-hugo/blob/master/content/specifications/vocabularies/_index.md

When live, it maps to:
https://oslc.github.io/specifications/vocabularies/

Let me know if that is an acceptable url.

**Comment by jamsden** [comment]
The pages are updated with initial content. The following vocabulary documents need to be migrated to OASIS to provide stable links for reference from open-services.net. None of these are migrated yet to OASIS, but we could migrate the vocabulary documents.

- rm.rdf
- qm.rdf
- am.rdf
- asset.rdf
- auto.rdf
- perfmon.rdf

I coped all of these files from open-services.net/ns to GitHub oslc-domains/open-services-vocabs to preserve them.

Then use these files to create domain-name-vocab.ttl files and domain-name-vocab.html files for all of the OSLC domains. 

Link all the HTML links in the table above to the domain-name-vocab.html files. Use the latest OASIS published URIs for published documents, use the latest in GitHub for unpublished files.

For all the RDF links, link to the published OASIS .ttl file if its available, otherwise link to the file in oslc-domains/domain-short-name.rdf.

**Comment by brianking** [comment]
@jamsden I already mirrored some RDF files in the ns/ (content/ns/) folder in the new repository. Are these different to what you are talking about?

**Comment by jamsden** [comment]
I need them mirrored on OASIS since the are the documents which are being migrated to the OASIS vocabularies. I simply copied the files from open-services.net/ns <http://open-services.net/ns> to the Domains TC GitHub repo. This is a more permanent place to put these documents. 

We may want to still use the ones you cloned for better performance instead of redirecting to GitHub. I’m not sure that would make much difference.

**Comment by brianking** [comment]
I guess another way of asking is, are the files at http://open-services.net/ns being used in a way that we have to preserve them there?

**Comment by berezovskyi** [comment]
Yes, I believe people might open the namespace URIs in an attempt to find a vocabulary definition and tools might try to load an RDFS schema (which they will fail, as it's not an RDFS schema _per se_).

I think that our and Jim's objectives are not orthogonal: Jim needs to archive the files for standardisation purposes, so that 3.0 specs can reliably refer to 2.0 artefacts, while we need those files archived for community consumption purposes. So I vote for keeping both rdf file copies where they are right now.

On the side note, I would love to see all specs split in 3 categories:

* draft specs
* active finalised specs
* superseded specs

I am not actually sure how many active finalised specs do we have now, e.g. Core 2.0 is superseded by 3.0 but 3.0 is still a draft :) But we can go into semantics after the site launch.

**Comment by jamsden** [comment]
I believe RDF/XML will need to be provided since that is what OSLC 2.0 users of the namespace documents are most likely expecting. 

If the server can support content negotiation, we can provide the vocabulary and shape files in other RDF serializations including Turtle and JSON-LD. But RDF/XML should be the minimum.

All the vocabularies and shapes available from OASIS document repositories or SCM systems (for draft versions) can be cloned to open-services.net if required for efficiency. But perhaps we should start by redirecting directly to OASIS to remove this additional publishing and maintenance step.

Lets try the redirects from http://oslc.co/ns, get it all working, and see if there's a big performance hit redirecting directly to OASIS. If so, then we can clone to http://oslc.co in order to improve performance.

**Comment by jamsden** [comment]
Summarizing where we are on this issue:

The vocabulary documents will be stored and maintained in the OASIS Domains TC GitHub: https://github.com/oasis-tcs/oslc-domains. The applicable files are typically {domain}-vocab.ttl and {domain}-shapes.ttl. 

When the OASIS documents are published as Committee Specification revisions, these documents will be published to the OASIS document repository and the latest version link will be updated. For example http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/oslc-core-v3.0-part1-overview.html. These are the normative OASIS documents, and all external links would typically be to these documents.

The vocabulary documents, vocab.ttl and shapes.ttl also need to be available from http://open-services.net/ns. OASIS doesn't support content negotiation, so we will need to also publish RDF/XML, Turtle, and JSON-LD versions of the vocab and shapes documents on the new open-services.net.

So the strategy will be on each publication of the OASIS specification revisions, we will also clone the *vocab.ttl and *shapes.ttl to http://open-services.net/ns/{domain}/{domain.ttl}. The .rdf and .jsonld files will be created from the .ttl file using a converter such as http://www.easyrdf.org. 

http://oslc.co/specifications/vocabularies/ provides a table with links to:

- The specifications - these are to the latest published OASIS document, or for the older domain specifications that have not yet been migrated, the PDF of the latest version copied from the old open-services.net/specifications to the OASIS Domains TC documents folder.

- Namespace URI - a GET on these URIs should return the RDF/XML the vocabulary. 

- RDF Schema - typically the same as the namespace, but may be turtle. These are currently linking to OASIS docs folder for published specifications (e.g., Core), or OASIS GitHub for unpublished domain specs. There's no content negotiation. These could be linked to the cloned versions in http://oslc.co/ns instead in order to support content negotiation

- HTML - the HTML versions of the vocabularies and shapes will be to the {domain}-vocab.html documents from OASIS. These use ReSpec to generate the HTML from the Turtle source.

What needs to be done is the current http://open-services.net/ns links need to be resolve or redirect to http://oslc.co/ns. and http://open-services.net/wiki/core/Vocabulary-index/ needs to redirect to http://oslc.co/specifications/vocabularies/.

**Comment by gabrielfdac** [comment]
Thanks Jim, so in when the new site is live and under open-services.net we'd have:

- http://open-services.net/wiki/core/Vocabulary-index/* -> http://oslc.co/specifications/vocabularies/
- http://open-services.net/ns/{domain}/ -> RDF/XML Vocabulary file
- http://open-services.net/ns/{domain}/{domain.ttl}: Instead of linking to oasis just grab the file already in /ns/*

Is that correct or I missed something?

Lastly you say you want to redirect from open-services.net/ns to oslc.co/ns. Would that be for testing? Or as a way to make sure we can do that? If so we'll need to make that redirect from the current server hosting open-services.net.

**Comment by berezovskyi** [comment]
I think the following should work when the new site goes live as it does now:

```curl -L -X GET \
  http://open-services.net/ns/core \
  -H 'Accept: text/turtle, application/rdf+xml, application/ld+json, application/n-triples, application/n-quads, application/owl+xml'```

And the idea there is that if you paste this URL into a browser, you see HTML, if you do the cURL request as given above, you get RDF.

Plus, vocabs now redirect to old pages, eg `http://open-services.net/ns/core` redirects to `http://open-services.net/wiki/core/CoreVocabulary/` when HTML is requested; people could have bookmarked those things. Thus, those "old redirect URLs" should also be re-redirected.

P.S. I don't think we should take the RDF files of the specs from OASIS unless Jim can confirm they are the finalised 2.0 versions, not 3.0 drafts.

**Comment by gabrielfdac** [comment]
Hi! Sorry for the delay to respond to this.

We're currently implementing and testing the redirects so that we can feel comfortable for launching the website.

Right now we are testing the different redirects of `/ns/{domain}` as a test, so it should accept the proper headers as of today. So give those a try if you can! 

However, while implementing it we got a couple of questions:

1. What will be the base redirect (no header) when a request is made to `/ns/{domain}`? Meaning if the user access that in the browser what would be the standard return, I was thinking that maybe we could try redirecting it from `/ns/{domain}` to `./specifications/vocabularies` since we don't have the specific html pages for each domain, let me know if there was anything specific in mind for this scenario.

2. We noticed that in this repository some domains have more than one vocabulary rdf file. (see [https://github.com/OSLC/oslc-site-hugo/tree/master/content/ns/core](https://github.com/OSLC/oslc-site-hugo/tree/master/content/ns/core) for instance) which has a `core.rdf` and a `core-vocab.rdf`, is there a difference between the two or should we only have one? Also, there are some domains with only the `{domain}-vocab.rdf` or `{domain}.rdf` variant. Some clarification here would be good.

Additionally http://oslc.co/wiki/core/vocabulary-index/ -> http://oslc.co/specifications/vocabularies/ is implemented. Note that the redirect is from oslc.co and not from open-services to oslc.co, this is purely for testing purposes but should represent the final redirect once we launch.

Let's get ready for launch!

**Comment by berezovskyi** [comment]
I believe the current handling is not correct:

```
$ curl http://oslc.co/ns/core \
  -H 'Accept: text/turtle, application/rdf+xml, application/ld+json, application/n-triples, application/n-quads, application/owl+xml' -i

HTTP/1.1 301 Moved Permanently
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 10 Oct 2018 21:30:56 GMT
Content-Type: text/html
Content-Length: 194
Location: http://oslc.co/ns/core/
Connection: keep-alive

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

I don't expect a redirect here but fine. Then:

```
$ curl http://oslc.co/ns/core/ \
  -H 'Accept: text/turtle, application/rdf+xml, application/ld+json, application/n-triples, application/n-quads, application/owl+xml' -i

HTTP/1.1 302 Moved Temporarily
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 10 Oct 2018 21:31:42 GMT
Content-Type: text/html
Content-Length: 170
Connection: keep-alive
Location: http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/oslc-core-v3.0-part7-core-vocabulary.html

<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

Which serves me non-RDF content **and** redirects me somewhere else w/o serving any RDF.

**Comment by berezovskyi** [comment]
also see https://github.com/OSLC/oslc-site-hugo/issues/2

**Comment by berezovskyi** [comment]
plus, there is overlap with #169

**Comment by berezovskyi** [comment]
@gabrielfdac here is the reply for your two questions:

1. If I open http://open-services.net/ns/core#AnyResource in the browser, I should get redirected to the right anchor as I do today. By default, browsers request HTML. "no header" situation can only arise if you have a poorly coded client. I would suggest returning RDF/XML in that case. Chrome requests a page with `text/html; charset=utf-8` MIME.

2. I expect to get the right RDF if I do cURL with `-L` option (follow redirects). https://harshp.com/dev/guides_tutorials/semantic-web/rdfowl-content-negotiation-using-nginx/ should produce the desired outcome.

**Comment by jamsden** [comment]
I have updated the specifications and specifications/vocabularies pages to refer to the latest documents.

**Comment by jamsden** [comment]
Once we verify the RDF serialization resources redirects, this can be closed.

**Comment by FabioRNT** [comment]
> I believe the current handling is not correct:
> 
> ```
> $ curl http://oslc.co/ns/core \
>   -H 'Accept: text/turtle, application/rdf+xml, application/ld+json, application/n-triples, application/n-quads, application/owl+xml' -i
> 
> HTTP/1.1 301 Moved Permanently
> Server: nginx/1.10.3 (Ubuntu)
> Date: Wed, 10 Oct 2018 21:30:56 GMT
> Content-Type: text/html
> Content-Length: 194
> Location: http://oslc.co/ns/core/
> Connection: keep-alive
> 
> <html>
> <head><title>301 Moved Permanently</title></head>
> <body bgcolor="white">
> <center><h1>301 Moved Permanently</h1></center>
> <hr><center>nginx/1.10.3 (Ubuntu)</center>
> </body>
> </html>
> ```
> I don't expect a redirect here but fine. Then:
> 
> ```
> $ curl http://oslc.co/ns/core/ \
>   -H 'Accept: text/turtle, application/rdf+xml, application/ld+json, application/n-triples, application/n-quads, application/owl+xml' -i
> 
> HTTP/1.1 302 Moved Temporarily
> Server: nginx/1.10.3 (Ubuntu)
> Date: Wed, 10 Oct 2018 21:31:42 GMT
> Content-Type: text/html
> Content-Length: 170
> Connection: keep-alive
> Location: http://docs.oasis-open.org/oslc-core/oslc-core/v3.0/oslc-core-v3.0-part7-core-vocabulary.html
> 
> <html>
> <head><title>302 Found</title></head>
> <body bgcolor="white">
> <center><h1>302 Found</h1></center>
> <hr><center>nginx/1.10.3 (Ubuntu)</center>
> </body>
> </html>
> ```
> Which serves me non-RDF content **and** redirects me somewhere else w/o serving any RDF.

@berezovskyi Right now the redirects are configured to answer according to the header. So, if you use curl -H 'Accept: application/rdf+xml', it will answer the vocab in rdf/xml format. If you change the header to 'Accept: application/ld+json' or 'Accept: text/turtle' it will answer in json-ld or ttl format. When you use multiple Accept values in your curl request, the redirects don't match and then it goes to the default redirect, which is the OASIS HTML page.

**Comment by FabioRNT** [comment]
@berezovskyi This kind of configuration is ok? Or should it be configured in a different way?

**Comment by gabrielfdac** [comment]
So how can we test if everything is correct with the redirects?

**Comment by berezovskyi** [comment]
@FabioRNT well, it's not. I understand the challenge but my request was 100% a correct HTTP request from the content negotiation point of view. I am afraid we might need a small webapp to handle this properly.

**Comment by berezovskyi** [comment]
https://github.com/golang/gddo/blob/master/httputil/negotiate.go#L43 or https://www.npmjs.com/package/accepts

**Comment by berezovskyi** [comment]
@FabioRNT please create a repo in your language/framework of choice and I will contribute to dev & test.

**Comment by gabrielfdac** [comment]
@berezovskyi so what you're saying is that with your request:

`curl http://oslc.co/ns/core \
  -H 'Accept: text/turtle, application/rdf+xml, application/ld+json, application/n-triples, application/n-quads, application/owl+xml' -i`

You're expecting all file types in return? Meaning you'd receive in return a .ttl, .rdf, .json... etc?

**Comment by berezovskyi** [comment]
No, I expect the server to return the first format with the highest priority that the server has. Here is a fuller test case:

`curl http://oslc.co/ns/core \ -H 'Accept: text/turtle, application/rdf+xml, application/ld+json, application/n-triples, application/n-quads, application/json;q=0.9,  application/rdf+json;q=0.8, text/*;q=0.5' -i`

In English: "I prefer Turtle, but RDF/XML is fine, and so are JSON-LD, N-Triples, N-Quads – in this order. If you don't have any of those, I _may_ be able to read JSON, RDF/JSON or any text file but I might not fully parse all the details in them".

A good explanation for this is here: http://restlet.com/company/blog/2015/12/10/understanding-http-content-negotiation/

**Comment by berezovskyi** [comment]
https://developer.mozilla.org/en-US/docs/Glossary/Quality_values

**Comment by berezovskyi** [comment]
Then the server may have its own table of "weights" (for example, we may have RDF/XML and Turtle as OASIS approved formats with q=1.0 and the rest will be generated via Jena command line tools with q=0.5) which it would multiply with the weights the client has provided (missing formats can be removed from the list at this step) and then would do a _stable sort_ of the remaining list of the acceptable formats. We can ignore the weights (also because HTTP spec allows us to) and just make sure to handle a list MIME types correctly.

**Comment by gabrielfdac** [comment]
Oh I see, we're trying to figure it out then. We'll let you know when we know more

**Comment by berezovskyi** [comment]
Ready to help if I can.

**Comment by FabioRNT** [comment]
Just implemented a node.js server to handle content negotiation for `oslc.co/ns/core` and the other specs. I've tested the redirects to OASIS in chrome and the `.rdf, .jsonld, and .ttl` files in postman, everything works on my end. I'll upload the code to the OSLC GitHub soon. @berezovskyi, can you test it to see if it is working as expected?

**Comment by berezovskyi** [comment]
@FabioRNT thanks a lot! Works really nicely. While playing with the endpoint, I had two thoughts:

1. Can we use the 303 See Other code for the last redirect. Because the `oslc.co/ns/core` is actually not moving anywhere.
2. Really nice touch returning 406 Not Acceptable for the unsupported formats but I think you are leaking a bit of Node info there.

`<pre>Error: Not Acceptable<br> &nbsp; &nbsp;at ServerResponse.res.format (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/response.js:675:15)<br> &nbsp; &nbsp;at /root/workspace/oslc-site-content-negotiation/negotiation.js:10:9<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbsp;at Route.dispatch (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /root/workspace/oslc-site-content-negotiation/node_modules/express/lib/router/index.js:281:22<br> &nbsp; &nbsp;at Function.process_params (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at expressInit (/root/workspace/oslc-site-content-negotiation/node_modules/express/lib/middleware/init.js:40:5)</pre>`

**Comment by berezovskyi** [comment]
triple checked everything 👌 thanks for the effort @FabioRNT @gabrielfdac
