### ISSUE TITLE
About - FAQ Content

### ISSUE THREAD

**Issue by brianking** [OSLC/oslc-site-hugo#19]
We have a participation FAQ here:

https://open-services.net/participate/faq/

However, much it will not be relevant anymore such as the parts about membership. Other parts we can put on other pages, e.g. steering committee on the Governance page.

So, what sort of questions should we be answering here?

**Comment by jamsden** [comment]
By nature a FAQ should be driven by the kinds of questions the community frequently asks. If open-services.net becomes a community focused on building and integrating things using OSLC, then its likely many of the existing FAQ elements won't be that useful. We perhaps won't know until we get some forum activity to see who is joining the community and what they want to know. We can probably seed a FAQ by making some things up that help community want we want to accomplish with the site.

**Comment by brianking** [comment]
Tagging @rersie for input.

**Comment by rersch** [comment]
Based on the recent e-mail conversion we had: we should clearly describe which OSLC channels exists (namely GitHub, Discourse, Slack, and Wiki) and what they should be used for including the need to create or use of existing logins. 
Other typical question which come up regularly:
- How can I get involved in OSLC
  A: User groups member, TC contributor, StC member, Reference implementation provider, Discourse participant, ...
- do I need to join OASIS in order to participate in the OSLC community?
   A: no - only for contributions to specifications or to elect or be elected for the steering committee
- What are the legal obligations to use OSLC Specs (license modeles, ...)
   A: free to use under ... license

The answers need to be worked on and there are probably some more, but that's what comes immediately into my mind.

**Comment by brianking** [comment]
Seeded some questions:
http://oslc.co/about/faq/

Instructions for adding a new entry:
https://github.com/OSLC/oslc-site-hugo/wiki/Adding-a-FAQ-Entry

Closing this issue now.

**Comment by axelreichwein** [comment]
These are questions I often face:

Why aren't OSLC specifications W3C standards?
What is the relationship between OSLC specifications and W3C standards?

What is the difference between OSLC and openAPI/Swagger?
What is the difference between OSLC and microservices?

What is the difference between OSLC and Open Data Protocol (OData)?
What is the difference between OSLC and GraphQL?
What is the difference between OSLC and smartAPI?

What is the difference between RDF and JSON?

**Comment by jamsden** [comment]
I will take a pass on these questions for the FAQ
