### ISSUE TITLE
Subtitle in landing page

### ISSUE THREAD

**Issue by axelreichwein** [OSLC/oslc-site-hugo#84]
Instead of "An open community building practical specifications for integrating **software**", the subtitle should be "An open community building practical specifications for integrating **data**", as OSLC can be used to provide a RESTful Linked Data API to any data source, such as databases, and not just to engineering software applications.

**Comment by LeoTrujillo** [comment]
ok @axelreichwein I'm working on it

**Comment by LeoTrujillo** [comment]
Ok, now the subtitle looks like this...
<img width="814" alt="c" src="https://user-images.githubusercontent.com/3343042/29321184-38e3bea2-819f-11e7-8d85-cdae9e449cfe.png">

Let me know what do you think @axelreichwein

**Comment by brianking** [comment]
Actually this was updated a couple of days ago, I just forgot to deploy it. After feedback from @rersch I changed it to:

"An open community building practical specifications to integrate data in engineering and software development environments"

@LeoTrujillo I think you regressed this change, because the last part if missing "....  in engineering and software development environments"

**Comment by brianking** [comment]
In issue #11 @rersch wrote:

We need to point out very strongly at a prominent spot that we are working on integration solutions for engineering/development environments and not on SW integration in general.
On place could be the text in the banner: e.g. "An open community building practical specifications to integrate data in engineering and SW development environments".

**Comment by LeoTrujillo** [comment]
@brianking So I have to change the text again like it was before?

**Comment by brianking** [comment]
@LeoTrujillo No, after talking with @axelreichwein some more about this, we can leave as-is. Closing.
